package qcspider.cli.options;

import org.apache.commons.cli.HelpFormatter;
import org.apache.commons.cli.Option;
import org.apache.commons.cli.Options;

public class OptionsBuilder
{
    /**
     * Create the list of options that will be used to process the request from the command line.
     * @return The set of options
     */
    public static Options getOptions()
    {
        Options options = new Options();
        options.addOption(new Option("h", "help", false, "Print this help."));
        options.addOption(new Option("v", "version", false, "Display version information."));
        options.addOption(
                Option.builder("c")
                      .longOpt("crawl")
                      .desc("Crawl the remote site as defined in the config file")
                      .hasArg()
                      .argName("config-path")
                      .build()
                         );
        options.addOption(new Option("t", "template", false, "Output a crawl settings template in the current directory"));
        return options;
    }

    /**
     * Output the help screen, autogenerated from the list of options.
     */
    public static void showHelp()
    {
        showHelp(getOptions());
    }

    /**
     * Outputs the help screen from the passed options.
     * @param options The list of optons
     */
    public static void showHelp(Options options)
    {
        HelpFormatter formatter = new HelpFormatter();
        formatter.printHelp("qcspider", options);
    }
}
