package qcspider.cli.options;

import org.apache.commons.cli.HelpFormatter;
import org.apache.commons.cli.Option;
import org.apache.commons.cli.Options;

public class OptionsBuilder
{
    /**
     * Create the list of options that will be used to process the request from the command line.
     * @return The set of options
     */
    public static Options getOptions()
    {
        Options options = new Options();
        options.addOption(new Option("help", "Print this help."));
        options.addOption(new Option("v", "Display version information."));
        options.addOption(
                Option.builder().argName("crawl").hasArg().desc("The path (relative or absolute) to the crawl settings file.").required().build()
                         );
        options.addOption(new Option("template", "Output a crawl settings template in the currend directory"));
        return options;
    }

    /**
     * Output the help screen, autogenerated from the list of options.
     */
    public static void showHelp()
    {
        showHelp(getOptions());
    }

    /**
     * Outputs the help screen from the passed options.
     * @param options
     */
    public static void showHelp(Options options)
    {
        HelpFormatter formatter = new HelpFormatter();
        formatter.printHelp("qcspider", options);
    }
}
